<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\RentFlow.Modules.Identity.Application\RentFlow.Modules.Identity.Application.csproj" />
    <ProjectReference Include="..\RentFlow.Modules.Identity.Presentation\RentFlow.Modules.Identity.Presentation.csproj" />
  </ItemGroup>
</Project>
